//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.1433
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IPositionService
{
    
    bool SendPosition(double latitude, double longitude, string remarks);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="SendPosition", Namespace="http://bruins/positionservice")]
public partial class SendPositionRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bruins/positionservice", Order=0)]
    public double latitude;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bruins/positionservice", Order=1)]
    public double longitude;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://bruins/positionservice", Order=2)]
    public string remarks;
    
    public SendPositionRequest()
    {
    }
    
    public SendPositionRequest(double latitude, double longitude, string remarks)
    {
        this.latitude = latitude;
        this.longitude = longitude;
        this.remarks = remarks;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="SendPositionResponse", Namespace="http://bruins/positionservice")]
public partial class SendPositionResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://bruins/positionservice", Order=0)]
    public bool SendPositionResult;
    
    public SendPositionResponse()
    {
    }
    
    public SendPositionResponse(bool SendPositionResult)
    {
        this.SendPositionResult = SendPositionResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class PositionServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IPositionService>, IPositionService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("");
    
    public PositionServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }

    public PositionServiceClient(string endPointAddress) :
        this(CreateDefaultBinding(), new System.ServiceModel.EndpointAddress(endPointAddress))
    {
    }

    public PositionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private SendPositionResponse SendPosition(SendPositionRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://bruins/positionservice/IPositionService/SendPosition";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://bruins/positionservice/IPositionService/SendPositionResponse";
        info.ResponseIsWrapped = true;
        SendPositionResponse retVal = base.Invoke<SendPositionRequest, SendPositionResponse>(info, request);
        return retVal;
    }
    
    public bool SendPosition(double latitude, double longitude, string remarks)
    {
        SendPositionRequest request = new SendPositionRequest(latitude, longitude, remarks);
        SendPositionResponse response = this.SendPosition(request);
        return response.SendPositionResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://bruins/positionservice/IPositionService/SendPosition", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://bruins/positionservice/IPositionService/SendPosition", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://bruins/positionservice/IPositionService/SendPositionResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://bruins/positionservice/IPositionService/SendPositionResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
